[build]
    base = "app"
    command = "npm run build:prod"
    publish = "dist/browser"
    functions = "netlify/functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/agent/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/sitemap.xml"
    to = "/sitemap.xml"
    status = 200

[[redirects]]
    from = "/robots.txt"
    to = "/robots.txt"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.csr.html"
    status = 200
